---
- name: "linux_helper | Include prereq tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "linux_helper | Include locale tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/locale/main.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_locale_settings',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Include deploy profile tasks"
  ansible.builtin.include_tasks:
    file: "deploy_profile.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_profile_settings',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Include deploy hostname tasks"
  ansible.builtin.include_tasks:
    file: "deploy_hostname.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_hostname_settings',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] is defined"
    - "hostvars[inventory_hostname]['linux_helper'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'linux_helper_set_hostname', default='')) == 'true'"
  vars:
    linux_helper_set_hostname: "[].hostname[] |
      map(&set_hostname || 'false', @) | [0]"
- name: "linux_helper | Include deploy hosts tasks"
  ansible.builtin.include_tasks:
    file: "deploy_hosts.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_hosts_settings',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] is defined"
    - "hostvars[inventory_hostname]['linux_helper'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'linux_helper_set_hosts', default='')) == 'true'"
  vars:
    linux_helper_set_hosts: "[].hosts[] | map(&set_hosts || 'false', @) | [0]"
- name: "linux_helper | Include modprobe executor"
  ansible.builtin.include_tasks:
    file: "modprobe_executor.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_modprobe_files',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] is defined"
    - "hostvars[inventory_hostname]['linux_helper'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'linux_helper_set_modprobe', default='')) == 'true'"
  vars:
    linux_helper_set_modprobe: "[].modprobe[] |
      map(&set_modprobe || 'false', @) | [0]"
- name: "linux_helper | Include deploy sudoers tasks"
  ansible.builtin.include_tasks:
    file: "deploy_sudoers.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_sudoers_settings',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Include deploy logrotate tasks"
  ansible.builtin.include_tasks:
    file: "deploy_logrotate.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_logrotate_settings',
      default='') | bool"

- name: "linux_helper | Include netconsole tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/netconsole/main.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_netconsole_settings',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] is defined"
    - "hostvars[inventory_hostname]['linux_helper'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'linux_helper_set_netconsole', default='')) == 'true'"
  vars:
    linux_helper_set_netconsole:
      "[].netconsole[] | map(&set_netconsole || 'false', @) | [0]"
- name: "linux_helper | Include deploy krb5 tasks"
  ansible.builtin.include_tasks:
    file: "deploy_krb5.yml"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper_krb5_settings',
      default='') not in ['', [], '[]', None]"
